version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  api:
    build:
      context: ./api/
      dockerfile: testing.Dockerfile
    depends_on:
      - db
    volumes:
      - ./api:/src
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - SECRET
      - API_PORT
      - DB_URL
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_TABLE

  web-app:
    build:
      context: ./web-app/
      dockerfile: testing.Dockerfile
    volumes:
      - ./web-app:/src
    ports:
      - ${WEB_APP_PORT}:${WEB_APP_PORT}
    environment:
      - PORT=${WEB_APP_PORT}
      - API_HOST
      - API_PORT
